version: '3.8'

services:
  vault:
    image: vault:1.13.3
    container_name: vault
    restart: always
    ports:
      - "8200:8200"
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault.hcl:/vault/config/vault.hcl:rw
      - ./data:/vault/data:rw
    command: |
      chmod 777 /vault/data
      vault server -config=/vault/config/vault.hcl
