version: '3.8'

services:
  vault:
    image: vault:1.13.3
    container_name: vault
    restart: always
    ports:
      - "8200:8200"
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault.hcl:vault.hcl
      - vault_data:/vault/data
    command: |
      mkdir data
      vault server -config=vault.hcl
volumes:
  vault_data:
