version: '3.8'

services:
  vault:
    image: vault:1.13.3
    container_name: vault
    restart: always
    ports:
      - "8200:8200"
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault.hcl:/vault/vault.hcl
      - vault_data:/vault/data
    command: vault server -config=/vault/vault.hcl
volumes:
  vault_data:
